[unstable]
# Rebuild core/compiler_builtins/alloc for our custom target; "mem" provides memcpy/memset etc.
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[build]
target = "x86_64-ignis.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
